spring.application.name=sentinel-core
server.port=8081

# --- H2 Database (In-Memory for Demo) ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.datasource.url=jdbc:h2:mem:fraud_db
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.generate-unique-name=false

# --- Kafka Connection (Secure for Public GitHub) ---
# Use Env Vars to avoid leaking your Aiven Cluster URL
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:SSL}

# SSL Configuration using placeholders
# Note: ${user.dir} is fine for local paths, but passwords should be externalized
spring.kafka.properties.ssl.truststore.type=JKS
spring.kafka.properties.ssl.truststore.location=${SSL_TRUSTSTORE_LOCATION}
spring.kafka.properties.ssl.truststore.password=${SSL_PASSWORD}

spring.kafka.properties.ssl.keystore.type=PKCS12
spring.kafka.properties.ssl.keystore.location=${SSL_KEYSTORE_LOCATION}
spring.kafka.properties.ssl.keystore.password=${SSL_PASSWORD}
spring.kafka.properties.ssl.key.password=${SSL_PASSWORD}

# --- Kafka Producer (Serialization) ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# --- Kafka Streams (Identity & Serdes) ---
# application-id acts as the Kafka Consumer Group
spring.kafka.streams.application-id=sentinel-engine-v1.0
spring.kafka.streams.properties.auto.offset.reset=earliest
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.springframework.kafka.support.serializer.JacksonJsonSerde
spring.kafka.streams.properties.spring.json.trusted.packages=com.byteentropy.sentinel_core.domain.model

# --- Fraud Rules Configuration ---
# Thresholds determine when to REVIEW or REJECT
fraud-engine.thresholds.high-amount=10000.00
fraud-engine.thresholds.review-score=40
fraud-engine.thresholds.reject-score=80

# Weights determine the impact of each triggered rule
fraud-engine.weights.high-amount-rule=55
fraud-engine.weights.blacklist-rule=100