name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # We skip tests here if they require a live Kafka connection
      # Or use 'mvn test' if you have Mockito/TopologyTestDriver tests
      run: mvn -B package --file pom.xml -DskipTests
